In [1]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

/home/secondvoca/anaconda3/envs/torch/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/home/secondvoca/anaconda3/envs/torch/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "

In [5]:
import torch

In [7]:
A = torch.tensor(A)
b = torch.tensor(b)

In [9]:
x, resid, rank, s = torch.linalg.lstsq(A, b)
print(x)
print(resid)
print(rank)
print(s)

tensor([-3.1271e+02, -1.1519e+02,  1.4500e+01, -1.1326e-01],
       dtype=torch.float64)
tensor([], dtype=torch.float64)
tensor(4)
tensor([], dtype=torch.float64)


- residual
  - $ \epsilon = A x - b $
- least norm problem
  - $ \epsilon^T \epsilon = \| \epsilon \|^2 = (Ax - b)^T(Ax - b) $
  - $ x = \mathrm{arg \, min_x} e^T e = \mathrm{arg \, min_x} (Ax - b)^T(Ax - b) $
- pseudo inverse
  - at, $ Ax \approx b, A^\dagger = (A^T A)^{-1}A^T $ 

In [17]:
X = torch.tensor(X)
y = torch.tensor(y)
pinv = torch.linalg.inv(X.T @ X) @ X.T
x_hat = pinv @ y
resid = (X @ x_hat - y).norm()
resid = resid**2
resid

/tmp/ipykernel_3181856/3767183457.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X)
/tmp/ipykernel_3181856/3767183457.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y)


tensor(12228.0463, dtype=torch.float64)

In [20]:
resid, torch.linalg.norm(X @ x_hat - y) ** 2

(tensor(12228.0463, dtype=torch.float64),
 tensor(12228.0463, dtype=torch.float64))

In [21]:
x, resid, rank, s = torch.linalg.lstsq(X, y)
resid

tensor([], dtype=torch.float64)

In [15]:
x

tensor([-9.2897e-02,  4.8715e-02, -4.0600e-03,  2.8540e+00, -2.8684e+00,
         5.9281e+00, -7.2693e-03, -9.6851e-01,  1.7115e-01, -9.3962e-03,
        -3.9219e-01,  1.4906e-02, -4.1630e-01], dtype=torch.float64)

In [16]:
x_hat

tensor([-9.2897e-02,  4.8715e-02, -4.0600e-03,  2.8540e+00, -2.8684e+00,
         5.9281e+00, -7.2693e-03, -9.6851e-01,  1.7115e-01, -9.3962e-03,
        -3.9219e-01,  1.4906e-02, -4.1630e-01], dtype=torch.float64)