- eigenvector and eigenvalue
$$ Av = \lambda v $$
- eigendecomposition
$$ A = V diag(\lambda) V^{-1} $$
- for the symmatric matrix
$$ A = Q \Lambda Q^T $$

In [1]:
import torch

In [4]:
x = torch.tensor([
  [0.5, 0],
  [0, 2]
], dtype=torch.float32)
y = torch.tensor([
  [0, 1],
  [1, 0]
], dtype=torch.float32)
print((y @ x))
print((y @ x) @ (y @ x))

tensor([[0.0000, 2.0000],
        [0.5000, 0.0000]])
tensor([[1., 0.],
        [0., 1.]])


In [6]:
x = torch.tensor([
  [-1, 0],
  [0, 2]
], dtype=torch.float32)
print(x.T)
print(x @ x)

tensor([[-1.,  0.],
        [ 0.,  2.]])
tensor([[1., 0.],
        [0., 4.]])
