In [1]:
import torch

- notations
  - scalar: $$ a \in \R$$
  - vector: $$ \bf{a} = \begin{bmatrix} a_1 \\ a_2 \\ \vdots \\ a_n \end{bmatrix} $$
  - matrix: $$ \bf{A} =
  \begin{bmatrix} 
  a_{11} & a_{12} \\
  a_{21} & a_{22} \\
  \end{bmatrix}  $$
  - tensor: $$ \mathrm{\bf{A}} $$
- operations
  - transpose
  - elementwise sum
  - scalar multiplication
  - broadcast

In [6]:
scalar = torch.tensor(3, dtype=torch.float32)
vector = torch.tensor([2, 3], dtype=torch.float32)
matrix = torch.tensor([
  [1, 2],
  [3, 4]
], dtype=torch.float32)

In [3]:
# transpose
matrix.T

tensor([[1., 3.],
        [2., 4.]])

In [4]:
# elementwise sum
matrix + matrix

tensor([[2., 4.],
        [6., 8.]])

In [5]:
# scalar multiplication
scalar * matrix

tensor([[ 3.,  6.],
        [ 9., 12.]])

In [7]:
# broadcast
matrix + vector

tensor([[3., 5.],
        [5., 7.]])

In [2]:
a = torch.tensor([
  [1, 2],
  [3, 4]
], dtype=torch.float32)
b = torch.tensor([
  [5, 6],
  [7, 8]
], dtype=torch.float32)

a @ b

tensor([[19., 22.],
        [43., 50.]])

In [3]:
a * b

tensor([[ 5., 12.],
        [21., 32.]])

- system of linear equations
$$ \bf{A} \textbf{\textit{x}} = \textbf{\textit{b}} $$
- identity matrix
$$ \forall \textbf{\textit{x}} \in \R^n $$
$$ \textbf{\textit{I}}_n \textbf{\textit{x}} = \textbf{\textit{x}} $$
- inverse matrix, matrix inverse
$$ \textbf{\textit{A}}^{-1} \textbf{\textit{A}} = \textbf{\textit{I}}_n $$

In [5]:
A = torch.tensor([
  [1, 3],
  [5, 3]
], dtype=torch.float32)

b = torch.tensor([4, 16], dtype=torch.float32)

A_inv = torch.inverse(A)

A_inv @ b

tensor([3.0000, 0.3333])