- linear combination
$$ Ax = \sum_i x_i A_{:, i} $$

- norm
$$ \|x\|_p = \left( \sum_i |x_i|^p \right)^\frac{1}{p} $$
$$ p \in \R,\, p \geq 1 $$
- p = 2, euclidean norm
- square L2 norm is good, since it's partial derivatives depense on it's each element.
- frobenius norm
$$ \|A\|_F = \sqrt{\sum_{i,j} A_{i, j}^2} $$

In [1]:
import torch

In [4]:
x = torch.randn(2)
fro = x.norm()
fro 

tensor(0.7741)

- diagonal matrix
- symmetric matrix
- orthogonal
- orthonormal

In [2]:
x = torch.tensor([1, 2])
print(x)
dia = torch.diag_embed(x)
print(dia)

tensor([1, 2])
tensor([[1, 0],
        [0, 2]])


In [8]:
x = torch.tensor([
  [1, 1],
  [-1, 1]
], dtype=torch.float32)
(x / x[0].norm()) @ (x / x[0].norm()).T

tensor([[1.0000, 0.0000],
        [0.0000, 1.0000]])

In [9]:
x = torch.tensor([
  [1, 0],
  [0, -1]
], dtype=torch.float32)
x @ x.T

tensor([[1., 0.],
        [0., 1.]])