- probability theory
- random variable
- probability distribution
- probability mass function
$$ P( \mathrm{x} = x)$$
- joint probability distribution
$$ P(\mathrm{x} = x, \, \mathrm{y} = y)$$
- requirements
  - P must be defined for all states of x.
  $$ \forall x \in \mathrm{x}, \, 0 \leq P(x) \leq 1 $$
  - normalization
  $$ \sum_x P(x) = 1 $$
  - a uniform distribution
  $$ P(\mathrm{x} = x_i) = \frac{1}{k} $$
- probability density function
  - P must be defined for all states of x.
  $$ \forall x \in \mathrm{x}, \, 0 \leq P(x) $$
  - normalization
  $$ \int P(x) \,dx = 1$$
- expectation, expected value
$$ \mathbb{E}_{x  \sim P} \left[ f(x) \right] = \int p(x)f(x) \,dx $$

In [1]:
import torch

In [8]:
x = torch.randn(10)
print(x)
print(x.mean())
f = lambda x: x**2
xm = (x - x.mean())
print(xm)
print(xm.mean())
v = f(xm)
print(v)
print(v.mean())

tensor([ 0.3250, -0.4395,  0.0967, -0.7909, -0.2663,  1.8120, -0.2740,  0.7401,
         0.0358, -1.4922])
tensor(-0.0253)
tensor([ 0.3503, -0.4142,  0.1221, -0.7656, -0.2409,  1.8373, -0.2487,  0.7654,
         0.0611, -1.4668])
tensor(-2.3842e-08)
tensor([0.1227, 0.1715, 0.0149, 0.5862, 0.0580, 3.3758, 0.0618, 0.5859, 0.0037,
        2.1516])
tensor(0.7132)


In [15]:
x = torch.linspace(1, 10, steps=9)
y = torch.linspace(2, 20, steps=9)
z = torch.linspace(10, 1, steps=9)

d = lambda t: t - t.mean()

cov_xy = (d(x) * d(y)).mean()
print(cov_xy)

cov_xz = (d(x) * d(z)).mean()
print(cov_xz)

tensor(16.8750)
tensor(-8.4375)


In [16]:
x = torch.rand(10) * 10
y = torch.rand(10) * 5

cov_xy = (d(x) * d(y)).mean()
print(cov_xy)

tensor(0.1494)


In [27]:
x = torch.rand(1000000) * 2 - 1
y = torch.randint(0, 2, (1000000,))
y = torch.where(y == 0, -1., 1.)

cov_xy = (d(x) * d(y)).mean()
print(cov_xy)

tensor(0.0002)
