- condition number

In [1]:
import torch

In [9]:
# making a matrix whos condition number is big.
# using eigen decomposition
r = torch.tensor([
  [1, 0],
  [0, 1e-3]
])
q = torch.tensor([
  [-1, 1],
  [1, 1]
], dtype=torch.float32)
a = q @ r @ q.T
a

tensor([[ 1.0010, -0.9990],
        [-0.9990,  1.0010]])

In [10]:
x1 = torch.tensor([1.1, 1], dtype=torch.float32)
x2 = torch.tensor([1.11, 1], dtype=torch.float32)
print(a @ x1)
print(a @ x2)

tensor([ 0.1021, -0.0979])
tensor([ 0.1121, -0.1079])


In [11]:
(0.1121-0.1021)/0.1021

0.0979431929480902