- learning
  - A computer program is said to learn from experience E with respect to some class of tasks T and performance measure P, if its performance at tasks in T, as measured by P, improves with experience E. - Mitchell(1997)
- class of tasks
  - classification: $ f: \R^n \rightarrow \{ 1,...,k\} $
  - classification with missing input
  - regression: $ f: \R^n \rightarrow \R $
  - transcription
  - machine translation
  - structured output
  - anomaly detection
  - synthesis and sampling
  - imputation of missing values
  - denoising
  - density estimation
- performance measure
  - accuracy
  - error rate: expected 0-1 loss
- experience

In [2]:
import torch

- linear regression
  - $ x \in \R^n, y \in \R $
  - $ \hat{y} = w^T x,\, w \in \R^n $
- mean squared error
  - $ mse = \frac{1}{m} \sum_{i} (\hat{y} - y)_i^2 $

In [7]:
w = torch.FloatTensor([1, 2])
x = torch.FloatTensor([
  [3,4],
  [5,6]
])

w @ x @ x.T @ w.reshape(-1, 1)

tensor([425.])

In [9]:
w @ w.reshape(-1, 1)

tensor([5.])

In [10]:
x @ x.T

tensor([[25., 39.],
        [39., 61.]])